In [1]:
import numpy as np 
import pandas as pd 
import datetime as datetime
import os

In [2]:
DATA_PATH = 'data/nyc-taxi/'
CSV_PATH = 'submissions/LGBM/v02'
CSV_SUBM_PATH = 'submissions/'

In [3]:
preds=[]

for filename in os.listdir(CSV_PATH):
    print(f'Adding {filename}')
    df = pd.read_csv(f'{CSV_PATH}/{filename}')
    preds.append(np.array(df.fare_amount))

Adding v02-Fold1.csv
Adding v02-Fold2.csv
Adding v02-Fold3.csv
Adding v02-Fold4.csv
Adding v02-Fold5.csv


In [4]:
preds

[array([10.53535996, 11.28066391,  4.11007541, ..., 54.01725715,
        18.92305983,  6.66983934]),
 array([10.41259409, 11.01060229,  4.0223259 , ..., 53.34312325,
        19.25243718,  6.57951471]),
 array([10.48164457, 11.12154347,  4.11182115, ..., 53.38849559,
        19.33742716,  6.78533194]),
 array([ 9.77266865, 10.95329209,  4.19606761, ..., 54.31319104,
        18.82560388,  6.80830027]),
 array([ 9.66802117, 10.33525235,  4.12296146, ..., 52.86254445,
        19.54666761,  6.73706581])]

In [5]:
predictions = np.mean(np.vstack([preds]),axis=0)
predictions

array([10.17405769, 10.94027082,  4.11265031, ..., 53.5849223 ,
       19.17703913,  6.71601042])

In [6]:
std = np.std(np.vstack([preds]),axis=0)
std

array([0.37396116, 0.3224564 , 0.05519163, ..., 0.51694657, 0.26685075,
       0.08310122])

In [7]:
np.max(std)

9.435359714067042

In [8]:
outdir = CSV_PATH
os.makedirs(outdir, exist_ok=True)
test_df_raw = pd.read_csv(f'{DATA_PATH}test.csv', usecols=['key'])

cur_dt = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
desc = 'vBlend_RF_' # description of submission for reference
ensemb_desc = '_E16_54M'
subm_fn =  desc + cur_dt + ensemb_desc + '.csv'
subm_path = f'{CSV_SUBM_PATH}{subm_fn}'

subm_path

'submissions/vBlend_RF_20180813_203525_E16_54M.csv'

In [9]:
# Create the CSV file
submission = pd.DataFrame(
    {'key': test_df_raw.key, 'fare_amount': predictions},
    columns = ['key', 'fare_amount'])
submission.to_csv(subm_path, index = False)

subm_path

'submissions/vBlend_RF_20180813_203525_E16_54M.csv'