In [10]:
import numpy as np 
import pandas as pd 
import datetime as datetime
import os

In [11]:
DATA_PATH = 'data/nyc-taxi/'
CSV_PATH = 'submissions/v11_ensemble_16trees_54M_rows_less_features'
CSV_SUBM_PATH = 'submissions/'

In [12]:
preds=[]

for filename in os.listdir(CSV_PATH):
    print(f'Adding {filename}')
    df = pd.read_csv(f'{CSV_PATH}/{filename}')
    preds.append(np.array(df.fare_amount))

Adding v11_RF_20180807_123140_01x16_54M.csv
Adding v11_RF_20180807_154337_01x16_54M.csv
Adding v11_RF_20180807_143508_01x16_54M.csv
Adding v11_RF_20180807_192052_01x16_54M.csv
Adding v11_RF_20180807_133212_01x16_54M.csv
Adding v11_RF_20180807_204053_01x16_54M.csv
Adding v11_RF_20180807_165319_01x16_54M.csv


In [13]:
preds

[array([ 9.73400298, 11.32776876,  4.08242063, ..., 54.91317501,
        17.27839782,  6.32260665]),
 array([11.13224206, 11.3171131 ,  4.32163691, ..., 54.74065776,
        18.53854164,  6.78206845]),
 array([ 9.95718119, 11.90494728,  4.31681548, ..., 54.92259962,
        17.37239697,  6.70600198]),
 array([10.04373665, 10.86551339,  4.25507936, ..., 56.21609598,
        17.21049852,  5.9969246 ]),
 array([10.07752976, 11.62089534,  4.00654761, ..., 54.63979216,
        17.9424479 ,  6.89373647]),
 array([10.3452381 , 11.38529266,  4.29857143, ..., 54.65214653,
        17.35985863,  7.09019661]),
 array([10.11889881, 11.76943204,  4.28131944, ..., 55.2782311 ,
        17.77294147,  6.79116725])]

In [14]:
predictions = np.mean(np.vstack([preds]),axis=0)
predictions

array([10.20126136, 11.4558518 ,  4.22319869, ..., 55.05181402,
       17.63929756,  6.65467172])

In [15]:
std = np.std(np.vstack([preds]),axis=0)
std

array([0.41615022, 0.31990856, 0.11667157, ..., 0.51672715, 0.44430363,
       0.34376656])

In [17]:
np.max(std)

7.222059420605692

In [18]:
outdir = CSV_PATH
os.makedirs(outdir, exist_ok=True)
test_df_raw = pd.read_csv(f'{DATA_PATH}test.csv', usecols=['key'])

cur_dt = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
desc = 'v11_RF_' # description of submission for reference
ensemb_desc = '_E07x16_54M'
subm_fn =  desc + cur_dt + ensemb_desc + '.csv'
subm_path = f'{CSV_SUBM_PATH}{subm_fn}'

subm_path

'submissions/v11_RF_20180807_125735_E07x16_54M.csv'

In [19]:
# Create the CSV file
submission = pd.DataFrame(
    {'key': test_df_raw.key, 'fare_amount': predictions},
    columns = ['key', 'fare_amount'])
submission.to_csv(subm_path, index = False)

subm_path

'submissions/v11_RF_20180807_125735_E07x16_54M.csv'