In [1]:
import numpy as np 
import pandas as pd 
import datetime as datetime
import os

In [2]:
DATA_PATH = 'data/nyc-taxi/'
CSV_PATH = 'submissions/all'
CSV_SUBM_PATH = 'submissions/'

In [3]:
preds=[]

for filename in os.listdir(CSV_PATH):
    print(f'Adding {filename}')
    df = pd.read_csv(f'{CSV_PATH}/{filename}')
    preds.append(np.array(df.fare_amount))

Adding v09_RF_20180803_014841_01x10_54M.csv
Adding v11_RF_20180808_033340_01x16_54M.csv
Adding v10_RF_20180805_065805_01x08_54M.csv
Adding v11_RF_20180807_123140_01x16_54M.csv
Adding v10_RF_20180805_034656_01x08_54M.csv
Adding v10_RF_20180805_080651_01x08_54M.csv
Adding v09_RF_20180802_165758_01x10_54M.csv
Adding v09_RF_20180802_153958_01x10_54M.csv
Adding v11_RF_20180807_154337_01x16_54M.csv
Adding v11_RF_20180808_021603_01x16_54M.csv
Adding v11_RF_20180808_045158_01x16_54M.csv
Adding v11_RF_20180807_143508_01x16_54M.csv
Adding v09_RF_20180803_002938_01x10_54M.csv
Adding v09_RF_20180802_140933_01x10_54M.csv
Adding v11_RF_20180807_192052_01x16_54M.csv
Adding v09_RF_20180802_214904_01x10_54M.csv
Adding v11_RF_20180808_072923_01x16_54M.csv
Adding v10_RF_20180805_055331_01x08_54M.csv
Adding v10_RF_20180805_101810_01x08_54M.csv
Adding v11_RF_20180807_133212_01x16_54M.csv
Adding v10_RF_20180805_044312_01x08_54M.csv
Adding v11_RF_20180808_061028_01x16_54M.csv
Adding v11_RF_20180808_005808_01

In [4]:
preds

[array([11.03255772, 11.09031746,  4.1400808 , ..., 52.57330888,
        17.99714286,  6.21416667]),
 array([10.21063988, 11.51977927,  4.71494044, ..., 54.68973341,
        16.89737103,  6.66648065]),
 array([11.63995536, 11.31586851,  4.31190477, ..., 54.21195901,
        17.02291667,  7.66145833]),
 array([ 9.73400298, 11.32776876,  4.08242063, ..., 54.91317501,
        17.27839782,  6.32260665]),
 array([10.29507576, 12.78541667,  4.73279761, ..., 55.23591142,
        18.08385417,  6.93156791]),
 array([10.10622294, 11.44866071,  3.94253967, ..., 54.84718847,
        16.77239811,  6.38611111]),
 array([10.09214286, 10.94375   ,  4.01733333, ..., 55.7102194 ,
        17.84795635,  7.09720418]),
 array([10.46401515, 10.28071429,  4.58733337, ..., 54.09086314,
        18.49416667,  6.40005952]),
 array([11.13224206, 11.3171131 ,  4.32163691, ..., 54.74065776,
        18.53854164,  6.78206845]),
 array([10.05683284, 11.62056052,  4.1617857 , ..., 54.74526935,
        19.17508676,  6.15

In [5]:
predictions = np.mean(np.vstack([preds]),axis=0)
predictions

array([10.43295035, 11.44336339,  4.36584996, ..., 54.74263429,
       17.56567418,  6.81029282])

In [6]:
std = np.std(np.vstack([preds]),axis=0)
std

array([0.55092641, 0.73256258, 0.45133351, ..., 0.7557321 , 0.57884955,
       0.76476433])

In [7]:
np.max(std)

8.406230238256619

In [8]:
outdir = CSV_PATH
os.makedirs(outdir, exist_ok=True)
test_df_raw = pd.read_csv(f'{DATA_PATH}test.csv', usecols=['key'])

cur_dt = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
desc = 'v11_RF_' # description of submission for reference
ensemb_desc = '_E32_54M'
subm_fn =  desc + cur_dt + ensemb_desc + '.csv'
subm_path = f'{CSV_SUBM_PATH}{subm_fn}'

subm_path

'submissions/v11_RF_20180808_001324_E32_54M.csv'

In [9]:
# Create the CSV file
submission = pd.DataFrame(
    {'key': test_df_raw.key, 'fare_amount': predictions},
    columns = ['key', 'fare_amount'])
submission.to_csv(subm_path, index = False)

subm_path

'submissions/v11_RF_20180808_001324_E32_54M.csv'