In [45]:
import numpy as np 
import pandas as pd 
import datetime as datetime
import os

In [46]:
DATA_PATH = 'data/nyc-taxi/'
CSV_PATH = 'submissions/to_merge/'
CSV_SUBM_PATH = 'submissions/'

In [47]:
preds=[]

for filename in os.listdir(CSV_PATH):
    print(f'Adding {filename}')
    df = pd.read_csv(f'{CSV_PATH}/{filename}')
    preds.append(np.array(df.fare_amount))

Adding v08_RF_20180802_101436_E18x10_50M.csv
Adding v09_RF_20180802_140933_01x10_54M.csv
Adding v09_RF_20180802_153958_01x10_54M.csv
Adding v09_RF_20180802_165758_01x10_54M.csv
Adding v09_RF_20180802_181652_01x10_54M.csv
Adding v09_RF_20180802_202857_01x10_54M.csv
Adding v09_RF_20180802_214904_01x10_54M.csv
Adding v09_RF_20180802_230846_01x10_54M.csv
Adding v09_RF_20180803_002938_01x10_54M.csv
Adding v09_RF_20180803_014841_01x10_54M.csv
Adding v10_RF_20180805_044312_01x08_54M.csv
Adding v10_RF_20180805_055331_01x08_54M.csv
Adding v10_RF_20180805_065805_01x08_54M.csv
Adding v10_RF_20180805_080651_01x08_54M.csv
Adding v10_RF_20180805_101810_01x08_54M.csv


In [48]:
preds

[array([10.67102139, 10.55133397,  4.30881233, ..., 52.69272353,
        17.97824515,  7.21483079]),
 array([10.37077381, 12.9115873 ,  4.4681905 , ..., 53.87035049,
        16.75      , 10.4775    ]),
 array([10.46401515, 10.28071429,  4.58733337, ..., 54.09086314,
        18.49416667,  6.40005952]),
 array([10.09214286, 10.94375   ,  4.01733333, ..., 55.7102194 ,
        17.84795635,  7.09720418]),
 array([10.39519841, 10.66806943,  4.19199999, ..., 55.32725094,
        18.31427779,  7.085     ]),
 array([10.19672619, 13.17233342,  4.18787303, ..., 55.74632984,
        17.55099998,  6.70369048]),
 array([ 9.6125    , 11.11869048,  4.63133334, ..., 54.37834178,
        17.6173214 ,  7.23166667]),
 array([10.79      , 11.10222222,  4.08633331, ..., 55.00038651,
        17.49700397,  6.44666667]),
 array([10.1422619 , 10.96630952,  6.41847618, ..., 54.75662583,
        16.90797622,  6.86083333]),
 array([11.03255772, 11.09031746,  4.1400808 , ..., 52.57330888,
        17.99714286,  6.21

In [49]:
predictions = np.mean(np.vstack([preds]),axis=0)

In [50]:
predictions

array([10.47648365, 11.26893295,  4.42511563, ..., 54.4953011 ,
       17.5640345 ,  7.07723851])

In [51]:
outdir = CSV_PATH
os.makedirs(outdir, exist_ok=True)
test_df_raw = pd.read_csv(f'{DATA_PATH}test.csv', usecols=['key'])

cur_dt = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
desc = 'v10_RF_' # description of submission for reference
ensemb_desc = '_E14x10_08_54M'
subm_fn =  desc + cur_dt + ensemb_desc + '.csv'
subm_path = f'{CSV_SUBM_PATH}{subm_fn}'

subm_path

'submissions/v10_RF_20180805_102829_E14x10_08_54M.csv'

In [52]:
# Create the CSV file
submission = pd.DataFrame(
    {'key': test_df_raw.key, 'fare_amount': predictions},
    columns = ['key', 'fare_amount'])
submission.to_csv(subm_path, index = False)

subm_path

'submissions/v10_RF_20180805_102829_E14x10_08_54M.csv'