In [1]:
import numpy as np 
import pandas as pd 
import datetime as datetime
import os

In [2]:
DATA_PATH = 'data/nyc-taxi/'
CSV_PATH = 'submissions/kaggle'
CSV_SUBM_PATH = 'submissions/'

In [11]:
preds=[]

for filename in os.listdir(CSV_PATH):
    print(f'Adding {filename}')
    df = pd.read_csv(f'{CSV_PATH}/{filename}')
    preds.append(np.array(df.fare_amount))

Adding lgsub.csv
Adding xgb.csv


In [12]:
preds

[array([ 9.3908498 , 10.37600714,  4.62309741, ..., 53.63826019,
        18.69262656,  6.30709243]),
 array([10.067607 , 11.218018 ,  4.9678683, ..., 52.398125 , 19.555742 ,
         6.8470435])]

In [13]:
predictions = np.mean(np.vstack([preds]),axis=0)
predictions

array([ 9.7292284 , 10.79701257,  4.79548286, ..., 53.0181926 ,
       19.12418428,  6.57706796])

In [14]:
std = np.std(np.vstack([preds]),axis=0)
std

array([0.3383786 , 0.42100543, 0.17238544, ..., 0.6200676 , 0.43155772,
       0.26997554])

In [15]:
np.max(std)

15.343621551686699

In [16]:
outdir = CSV_PATH
os.makedirs(outdir, exist_ok=True)
test_df_raw = pd.read_csv(f'{DATA_PATH}test.csv', usecols=['key'])

cur_dt = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
desc = 'v15_RF_' # description of submission for reference
ensemb_desc = '_E16_54M'
subm_fn =  desc + cur_dt + ensemb_desc + '.csv'
subm_path = f'{CSV_SUBM_PATH}{subm_fn}'

subm_path

'submissions/v15_RF_20180811_163520_E16_54M.csv'

In [17]:
# Create the CSV file
submission = pd.DataFrame(
    {'key': test_df_raw.key, 'fare_amount': predictions},
    columns = ['key', 'fare_amount'])
submission.to_csv(subm_path, index = False)

subm_path

'submissions/v15_RF_20180811_163520_E16_54M.csv'