In [1]:
import numpy as np 
import pandas as pd 
import datetime as datetime
import os

In [2]:
DATA_PATH = 'data/nyc-taxi/'
CSV_PATH = 'submissions/v15_ensemble_16trees_54M'
CSV_SUBM_PATH = 'submissions/'

In [3]:
preds=[]

for filename in os.listdir(CSV_PATH):
    print(f'Adding {filename}')
    df = pd.read_csv(f'{CSV_PATH}/{filename}')
    preds.append(np.array(df.fare_amount))

Adding v15_RF_20180809_005302_01x16_54M.csv
Adding v15_RF_20180809_052141_01x16_54M.csv
Adding v15_RF_20180809_082725_01x16_54M.csv
Adding v15_RF_20180809_094148_01x16_54M.csv
Adding v15_RF_20180809_044750_01x16_54M.csv
Adding v15_RF_20180809_041318_01x16_54M.csv
Adding v15_RF_20180809_105618_01x16_54M.csv
Adding v15_RF_20180809_074938_01x16_54M.csv
Adding v15_RF_20180809_012432_01x16_54M.csv
Adding v15_RF_20180809_071213_01x16_54M.csv
Adding v15_RF_20180809_063434_01x16_54M.csv
Adding v15_RF_20180809_034011_01x16_54M.csv
Adding v15_RF_20180809_090451_01x16_54M.csv
Adding v15_RF_20180809_055720_01x16_54M.csv
Adding v15_RF_20180809_030739_01x16_54M.csv
Adding v15_RF_20180809_015723_01x16_54M.csv
Adding v15_RF_20180809_101832_01x16_54M.csv


In [4]:
preds

[array([10.75806728, 11.2015625 ,  4.00658729, ..., 53.92058379,
        18.06393849,  7.0188244 ]),
 array([10.35416667, 11.2327877 ,  4.32690474, ..., 55.50080281,
        18.02656995,  6.80373828]),
 array([10.10505952, 12.36464886,  4.59084326, ..., 54.51660889,
        17.8797247 ,  6.67579816]),
 array([10.09809028, 11.04720982,  4.20922621, ..., 54.64967033,
        17.11221478,  7.20096726]),
 array([10.38182043, 11.05096726,  4.33133115, ..., 54.16620854,
        17.05677083,  6.38862847]),
 array([10.47377614, 11.65815183,  4.2807143 , ..., 54.22536674,
        18.48162202,  6.53164683]),
 array([10.54825149, 11.46078869,  4.55788691, ..., 52.07165969,
        18.43254419,  6.84303075]),
 array([ 9.57700893, 12.18366815,  5.47870041, ..., 54.45776111,
        17.28446182,  7.07542614]),
 array([ 9.80432788, 10.97780258,  4.32727274, ..., 54.71707352,
        18.18335813,  6.50863095]),
 array([10.65900298, 11.16052827,  4.35848213, ..., 55.2797145 ,
        17.01510417,  6.55

In [5]:
predictions = np.mean(np.vstack([preds]),axis=0)
predictions

array([10.32132429, 11.35615627,  4.42949355, ..., 54.25544354,
       17.86355506,  6.80624357])

In [6]:
std = np.std(np.vstack([preds]),axis=0)
std

array([0.38296386, 0.5421122 , 0.3446015 , ..., 0.76288754, 0.59975302,
       0.31174095])

In [7]:
np.max(std)

9.517959262360097

In [10]:
outdir = CSV_PATH
os.makedirs(outdir, exist_ok=True)
test_df_raw = pd.read_csv(f'{DATA_PATH}test.csv', usecols=['key'])

cur_dt = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
desc = 'v15_RF_' # description of submission for reference
ensemb_desc = '_E16_54M'
subm_fn =  desc + cur_dt + ensemb_desc + '.csv'
subm_path = f'{CSV_SUBM_PATH}{subm_fn}'

subm_path

'submissions/v15_RF_20180809_031517_E16_54M.csv'

In [11]:
# Create the CSV file
submission = pd.DataFrame(
    {'key': test_df_raw.key, 'fare_amount': predictions},
    columns = ['key', 'fare_amount'])
submission.to_csv(subm_path, index = False)

subm_path

'submissions/v15_RF_20180809_031517_E16_54M.csv'