In [17]:
import numpy as np 
import pandas as pd 
import datetime as datetime
import os

In [18]:
DATA_PATH = 'data/nyc-taxi/'
CSV_PATH = 'submissions/v11_ensemble_16trees_54M_rows'
CSV_SUBM_PATH = 'submissions/'

In [19]:
preds=[]

for filename in os.listdir(CSV_PATH):
    print(f'Adding {filename}')
    df = pd.read_csv(f'{CSV_PATH}/{filename}')
    preds.append(np.array(df.fare_amount))

Adding v11_RF_20180807_000517_01x16_54M.csv
Adding v11_RF_20180807_010408_01x16_54M.csv
Adding v11_RF_20180807_014810_01x16_54M.csv
Adding v11_RF_20180807_023509_01x16_54M.csv
Adding v11_RF_20180807_032339_01x16_54M.csv
Adding v11_RF_20180807_041537_01x16_54M.csv
Adding v11_RF_20180807_050807_01x16_54M.csv
Adding v11_RF_20180807_060506_01x16_54M.csv
Adding v11_RF_20180807_070148_01x16_54M.csv
Adding v11_RF_20180807_080141_01x16_54M.csv
Adding v11_RF_20180807_090137_01x16_54M.csv
Adding v11_RF_20180807_100149_01x16_54M.csv


In [20]:
preds

[array([10.10403026, 12.73460818,  4.14502977, ..., 54.96116749,
        17.4061756 ,  6.87671131]),
 array([10.90245536, 12.05974416,  4.23335318, ..., 54.76618819,
        16.74000494,  7.34107143]),
 array([10.28896329, 10.48680556,  4.60931818, ..., 55.90584918,
        17.18927329,  7.19605655]),
 array([10.4328249 , 12.80780912,  4.18800595, ..., 54.63073586,
        17.07178663,  6.70094359]),
 array([10.75668966, 11.92734501,  3.98395833, ..., 55.10529299,
        17.79970238,  7.36460813]),
 array([10.30894097, 11.17320188,  4.10773807, ..., 54.09554748,
        17.54164976,  6.73346974]),
 array([10.15267519, 10.58700397,  4.27229167, ..., 55.54855309,
        16.70398065,  6.89272524]),
 array([10.46006944, 11.9671627 ,  4.39815478, ..., 55.29026133,
        17.77622768,  7.80648562]),
 array([10.30771104, 11.1812996 ,  4.11796446, ..., 54.80050827,
        17.54378833,  6.62220982]),
 array([10.37916667, 11.21346726,  4.23302961, ..., 55.18138639,
        18.50088045,  7.50

In [13]:
predictions = np.mean(np.vstack([preds]),axis=0)
predictions

In [14]:
std = np.std(np.vstack([preds]),axis=0)
std

array([10.51201584, 11.42934961,  4.35303724, ..., 54.72834424,
       17.49703532,  7.0507289 ])

In [37]:
np.max(std)

9.180028497630296

In [15]:
outdir = CSV_PATH
os.makedirs(outdir, exist_ok=True)
test_df_raw = pd.read_csv(f'{DATA_PATH}test.csv', usecols=['key'])

cur_dt = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
desc = 'v11_RF_' # description of submission for reference
ensemb_desc = '_E28_54M'
subm_fn =  desc + cur_dt + ensemb_desc + '.csv'
subm_path = f'{CSV_SUBM_PATH}{subm_fn}'

subm_path

'submissions/v11_RF_20180807_102314_E28_54M.csv'

In [16]:
# Create the CSV file
submission = pd.DataFrame(
    {'key': test_df_raw.key, 'fare_amount': predictions},
    columns = ['key', 'fare_amount'])
submission.to_csv(subm_path, index = False)

subm_path

'submissions/v11_RF_20180807_102314_E28_54M.csv'