In [1]:
import numpy as np 
import pandas as pd 
import datetime as datetime
import os

In [2]:
DATA_PATH = 'data/nyc-taxi/'
CSV_PATH = 'submissions/LGBM/ensemble'
CSV_SUBM_PATH = 'submissions/'

In [3]:
preds=[]

for filename in os.listdir(CSV_PATH):
    print(f'Adding {filename}')
    df = pd.read_csv(f'{CSV_PATH}/{filename}')
    preds.append(np.array(df.fare_amount))

Adding 10.csv
Adding 2.csv
Adding 8.csv
Adding 9.csv


In [4]:
preds

[array([10.22197445, 11.08831508,  4.17517369, ..., 53.95637001,
        18.93050178,  6.64195485]),
 array([10.16678196, 11.06559289,  4.12398327, ..., 53.79930154,
        18.9709093 ,  6.61179785]),
 array([10.36446704, 11.22247486,  4.24037207, ..., 54.28110097,
        19.12639853,  6.75438358]),
 array([10.29523232, 11.08948516,  4.25666449, ..., 54.00598513,
        19.39426461,  6.70039688])]

In [5]:
predictions = np.mean(np.vstack([preds]),axis=0)
predictions

array([10.26211394, 11.116467  ,  4.19904838, ..., 54.01068941,
       19.10551855,  6.67713329])

In [6]:
std = np.std(np.vstack([preds]),axis=0)
std

array([0.07461962, 0.06194028, 0.05299065, ..., 0.17376707, 0.18204449,
       0.05480658])

In [7]:
np.max(std)

12.765311767708189

In [9]:
outdir = CSV_PATH
os.makedirs(outdir, exist_ok=True)
test_df_raw = pd.read_csv(f'{DATA_PATH}test.csv', usecols=['key'])

cur_dt = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
desc = 'v15_RF_' # description of submission for reference
ensemb_desc = '_E16_54M'
subm_fn =  'merged.csv' #desc + cur_dt + ensemb_desc + '.csv'
subm_path = f'{CSV_SUBM_PATH}{subm_fn}'

subm_path

'submissions/merged.csv'

In [10]:
# Create the CSV file
submission = pd.DataFrame(
    {'key': test_df_raw.key, 'fare_amount': predictions},
    columns = ['key', 'fare_amount'])
submission.to_csv(subm_path, index = False)

subm_path

'submissions/merged.csv'