In [1]:
import numpy as np 
import pandas as pd 
import datetime as datetime
import os

/home/szelee/anaconda3/envs/fastai/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/szelee/anaconda3/envs/fastai/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
DATA_PATH = 'data/nyc-taxi/'
CSV_PATH = 'submissions/v10_ensemble_08trees_54M_rows/'
CSV_SUBM_PATH = 'submissions/'

In [3]:
preds=[]

for filename in os.listdir(CSV_PATH):
    print(f'Adding {filename}')
    df = pd.read_csv(f'{CSV_PATH}/{filename}')
    preds.append(np.array(df.fare_amount))

Adding v10_RF_20180805_065805_01x08_54M.csv
Adding v10_RF_20180805_034656_01x08_54M.csv
Adding v10_RF_20180805_080651_01x08_54M.csv
Adding v10_RF_20180805_055331_01x08_54M.csv
Adding v10_RF_20180805_044312_01x08_54M.csv
Adding v10_RF_20180805_091132_01x08_54M.csv


In [4]:
preds

[array([11.63995536, 11.31586851,  4.31190477, ..., 54.21195901,
        17.02291667,  7.66145833]),
 array([10.29507576, 12.78541667,  4.73279761, ..., 55.23591142,
        18.08385417,  6.93156791]),
 array([10.10622294, 11.44866071,  3.94253967, ..., 54.84718847,
        16.77239811,  6.38611111]),
 array([ 9.72534722, 10.65885417,  3.9966667 , ..., 54.21436293,
        17.840023  ,  6.92916667]),
 array([11.06746032, 12.378125  ,  4.77000003, ..., 55.23498011,
        17.86041664,  6.3578125 ]),
 array([12.19355159, 10.88333333,  4.15285714, ..., 54.23571587,
        16.38787202,  5.92842262])]

In [5]:
predictions = np.mean(np.vstack([preds]),axis=0)

In [6]:
predictions

array([10.83793553, 11.5783764 ,  4.31779432, ..., 54.66335297,
       17.32791343,  6.69908986])

In [7]:
outdir = CSV_PATH
os.makedirs(outdir, exist_ok=True)
test_df_raw = pd.read_csv(f'{DATA_PATH}test.csv', usecols=['key'])

cur_dt = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
desc = 'v10_RF_' # description of submission for reference
ensemb_desc = '_E06x08_54M'
subm_fn =  desc + cur_dt + ensemb_desc + '.csv'
subm_path = f'{CSV_SUBM_PATH}{subm_fn}'

subm_path

'submissions/v10_RF_20180805_021028_E06x08_54M.csv'

In [8]:
# Create the CSV file
submission = pd.DataFrame(
    {'key': test_df_raw.key, 'fare_amount': predictions},
    columns = ['key', 'fare_amount'])
submission.to_csv(subm_path, index = False)

subm_path

'submissions/v10_RF_20180805_021028_E06x08_54M.csv'