In [1]:
import numpy as np 
import pandas as pd 
import datetime as datetime
import os

In [2]:
DATA_PATH = 'data/nyc-taxi/'
CSV_PATH = 'submissions/v08_ensemble_10trees_50M_rows/'
CSV_SUBM_PATH = 'submissions/'

In [3]:
preds=[]

for filename in os.listdir(CSV_PATH):
    print(f'Adding {filename}')
    df = pd.read_csv(f'{CSV_PATH}/{filename}')
    preds.append(np.array(df.fare_amount))

Adding v08_RF_20180801_005735_01x10_50M.csv
Adding v08_RF_20180801_122651_01x10_50M.csv
Adding v08_RF_20180801_132914_01x10_50M.csv
Adding v08_RF_20180801_142012_01x10_50M.csv
Adding v08_RF_20180801_151113_01x10_50M.csv
Adding v08_RF_20180801_160133_01x10_50M.csv
Adding v08_RF_20180801_165358_01x10_50M.csv
Adding v08_RF_20180801_212654_01x10_50M.csv
Adding v08_RF_20180801_221758_01x10_50M.csv
Adding v08_RF_20180801_231059_01x10_50M.csv
Adding v08_RF_20180802_005832_01x10_50M.csv
Adding v08_RF_20180802_015009_01x10_50M.csv
Adding v08_RF_20180802_024115_01x10_50M.csv
Adding v08_RF_20180802_033401_01x10_50M.csv
Adding v08_RF_20180802_042403_01x10_50M.csv
Adding v08_RF_20180802_051524_01x10_50M.csv
Adding v08_RF_20180802_060711_01x10_50M.csv
Adding v08_RF_20180802_065756_01x10_50M.csv


In [4]:
preds

[array([ 9.98174603,  9.63363095,  3.89219049, ..., 52.93833361,
        17.97361111,  7.0639881 ]),
 array([ 9.42498015, 10.475     ,  4.22485711, ..., 52.53640341,
        18.20382937,  6.40767857]),
 array([10.46847222, 10.18470238,  4.14547619, ..., 53.66868502,
        18.08119048,  8.15069444]),
 array([10.67007937, 10.18605159,  4.13971428, ..., 52.59861348,
        16.91750003,  7.1572619 ]),
 array([10.24309524, 10.04541667,  4.4013622 , ..., 50.60035042,
        18.38744048,  6.49607143]),
 array([11.25007937, 12.25569444,  4.45523811, ..., 52.46560074,
        18.50694444,  7.30952381]),
 array([10.38738095, 10.84547619,  4.19955553, ..., 50.71090883,
        17.94396825,  6.4552381 ]),
 array([10.52863095, 10.88319805,  4.3064762 , ..., 52.47482478,
        18.34410714,  8.70845238]),
 array([10.3505303 , 11.37698413,  5.91504763, ..., 54.91910096,
        17.48884921,  7.80708333]),
 array([11.06756494, 11.05922619,  4.06761905, ..., 50.26389115,
        17.97166667,  6.88

In [5]:
predictions = np.mean(np.vstack([preds]),axis=0)

In [6]:
predictions

array([10.67102139, 10.55133397,  4.30881233, ..., 52.69272353,
       17.97824515,  7.21483079])

In [8]:
outdir = CSV_PATH
os.makedirs(outdir, exist_ok=True)
test_df_raw = pd.read_csv(f'{DATA_PATH}test.csv', usecols=['key'])

cur_dt = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
desc = 'v08_RF_' # description of submission for reference
ensemb_desc = '_E10x10_50M'
subm_fn =  desc + cur_dt + ensemb_desc + '.csv'
subm_path = f'{CSV_SUBM_PATH}{subm_fn}'

subm_path

'submissions/v08_RF_20180802_133648_E10x10_50M.csv'

In [11]:
# Create the CSV file
submission = pd.DataFrame(
    {'key': test_df_raw.key, 'fare_amount': predictions},
    columns = ['key', 'fare_amount'])
submission.to_csv(subm_path, index = False)

subm_path

'submissions/v08_RF_20180802_133648_E10x10_50M.csv'