In [1]:
import numpy as np 
import pandas as pd 
import datetime as datetime
import os

In [2]:
DATA_PATH = 'data/nyc-taxi/'
CSV_PATH = 'submissions/RF'
CSV_SUBM_PATH = 'submissions/'

In [3]:
preds=[]

for filename in os.listdir(CSV_PATH):
    print(f'Adding {filename}')
    df = pd.read_csv(f'{CSV_PATH}/{filename}')
    preds.append(np.array(df.fare_amount))

Adding Final_RF_20180924_031054_01x16_54M.csv
Adding Final_RF_20180924_054008_01x16_54M.csv
Adding Final_RF_20180924_081714_01x16_54M.csv


In [4]:
preds

[array([10.32260326, 12.13040184,  4.36650073, ..., 54.0954859 ,
        17.32678571,  6.60609894]),
 array([10.95815972, 11.4721388 ,  4.47426742, ..., 54.61074624,
        16.36700148,  7.13712798]),
 array([10.36941288, 11.74102408,  4.26160715, ..., 53.75585967,
        17.84311754,  6.69795387])]

In [5]:
predictions = np.mean(np.vstack([preds]),axis=0)
predictions

array([10.55005862, 11.78118824,  4.36745843, ..., 54.1540306 ,
       17.17896824,  6.81372693])

In [6]:
std = np.std(np.vstack([preds]),axis=0)
std

array([0.28920312, 0.27023129, 0.08682083, ..., 0.35145258, 0.61161925,
       0.23173334])

In [7]:
np.max(std)

8.168920087404235

In [9]:
outdir = CSV_PATH
os.makedirs(outdir, exist_ok=True)
test_df_raw = pd.read_csv(f'{DATA_PATH}test.csv', usecols=['key'])

cur_dt = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
desc = 'RF_' # description of submission for reference
ensemb_desc = '_Final'
subm_fn =  desc + cur_dt + ensemb_desc + '.csv'
subm_path = f'{CSV_SUBM_PATH}{subm_fn}'

subm_path

'submissions/RF_20180924_084257_Final.csv'

In [10]:
# Create the CSV file
submission = pd.DataFrame(
    {'key': test_df_raw.key, 'fare_amount': predictions},
    columns = ['key', 'fare_amount'])
submission.to_csv(subm_path, index = False)

subm_path

'submissions/RF_20180924_084257_Final.csv'