In [9]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2

In [10]:
import lightgbm as lgb
import numpy as np
import pandas as pd

In [3]:
n = 100
# construct an example in which the y-value is just the parity of the first column of X
X = np.array([np.random.randint(0,10, size=n), np.random.normal(size=n)]).transpose()

In [4]:
y = X[:,0]%2

In [5]:
# 1. train, stipulating that the first column is categorical
ds = lgb.Dataset(X, y, categorical_feature=[0])
params = {'objective':'regression_l2',  'metric':'rmse'}
gbm = lgb.train(params, ds,num_boost_round=10, valid_sets=[ds])

[1]	training's rmse: 0.497432
[2]	training's rmse: 0.495668
[3]	training's rmse: 0.494236
[4]	training's rmse: 0.493072
[5]	training's rmse: 0.492127
[6]	training's rmse: 0.491188
[7]	training's rmse: 0.490417
[8]	training's rmse: 0.489644
[9]	training's rmse: 0.489003
[10]	training's rmse: 0.488483


C:\Users\szelee\Anaconda3\envs\tf\lib\site-packages\lightgbm\basic.py:1040: UserWarning: Using categorical_feature in Dataset.
  warnings.warn('Using categorical_feature in Dataset.')


In [6]:
# 2. training, except we don't set anything as categorical.  Exact same as #1.
ds = lgb.Dataset(X, y)
params = {'objective':'regression_l2',  'metric':'rmse'}
gbm = lgb.train(params, ds,num_boost_round=10, valid_sets=[ds])

[1]	training's rmse: 0.494252
[2]	training's rmse: 0.489878
[3]	training's rmse: 0.486306
[4]	training's rmse: 0.483393
[5]	training's rmse: 0.481121
[6]	training's rmse: 0.478139
[7]	training's rmse: 0.47605
[8]	training's rmse: 0.47327
[9]	training's rmse: 0.470799
[10]	training's rmse: 0.468565


In [7]:
#3. now, set the categorical_feature in train().  This gives a different output than above.
ds = lgb.Dataset(X, y, categorical_feature=[0])
params = {'objective':'regression_l2',  'metric':'rmse'}
gbm = lgb.train(params, ds,num_boost_round=10, valid_sets=[ds], categorical_feature=[0])

[1]	training's rmse: 0.497432
[2]	training's rmse: 0.495668
[3]	training's rmse: 0.494236
[4]	training's rmse: 0.493072
[5]	training's rmse: 0.492127
[6]	training's rmse: 0.491188
[7]	training's rmse: 0.490417
[8]	training's rmse: 0.489644
[9]	training's rmse: 0.489003
[10]	training's rmse: 0.488483


In [8]:
# 4. what if we don't bother with categorical_feature in the lgb.Dataset definition?  
#     same thing as #3.
ds = lgb.Dataset(X, y)
params = {'objective':'regression_l2',  'metric':'rmse'}
gbm = lgb.train(params, ds,num_boost_round=10, valid_sets=[ds], categorical_feature=[0])

[1]	training's rmse: 0.497432
[2]	training's rmse: 0.495668
[3]	training's rmse: 0.494236
[4]	training's rmse: 0.493072
[5]	training's rmse: 0.492127
[6]	training's rmse: 0.491188
[7]	training's rmse: 0.490417
[8]	training's rmse: 0.489644
[9]	training's rmse: 0.489003
[10]	training's rmse: 0.488483


C:\Users\szelee\Anaconda3\envs\tf\lib\site-packages\lightgbm\basic.py:1042: UserWarning: categorical_feature in Dataset is overridden. New categorical_feature is [0]
  warnings.warn('categorical_feature in Dataset is overridden. New categorical_feature is {}'.format(sorted(list(categorical_feature))))


In [12]:
X = np.random.randint(1,10,(4,4))

In [13]:
X

array([[7, 4, 3, 7],
       [9, 5, 5, 3],
       [9, 9, 6, 5],
       [7, 7, 6, 5]])

In [14]:
X[1]

array([9, 5, 5, 3])

In [15]:
idx = [0,3]

In [16]:
X[idx]

array([[7, 4, 3, 7],
       [7, 7, 6, 5]])